import more from "../Assets/allRest/more.jpg";


const AllRestaurantData = [
  {
    id: 1,
    name: "Kangaroo HOP 待待超市",
    img:more,
    charge: 290,
    mark: 4.5,
    distance: 1.3,
    time: "15 - 30",
    discount: 30,
    美食類型: ["生活百貨"],
    生活百貨優惠: true,
    提供純素選擇: true,
    有機食品: true,
    素食: true,
    comment: "(500+)",
    special: "待待送 Kangaroo 獨家",
  },
  {
    id:2,
    name: "十分飽 Ten Mark Full",
    img: more,
    hot: true,
    charge: 290,
    mark: 4.5,
    distance: 1.3,
    time: "25 - 30",
    discount: 30,
    美食類型: ["亞洲菜", "新派亞洲菜", "港式菜"],
    菜式: ["便當", "意大利粉", "炸雞", "雞翼", "雞肉", "餃子"],
    comment: "(500+)",
    special: "待待送 Kangaroo 獨家",
  },
  {
    id: 3,
    name: "天地甜品 Tin They Dessert",
    img: more,
    hot: true,
    mark: 4.6,
    distance: 0.9,
    time: "20 - 35",
    discount: "免運費",
    美食類型: ["飲品"],
    菜式: ["甜品"],
    comment: "(500+)",
    special: "待待送 Kangaroo 獨家",
  },
  {
    id: 4,
    name: "壽司府 Sushifu",
    img: more,
    hot: true,
    mark: 4.6,
    distance: 1.1,
    time: "40 - 45",
    discount: "免運費",
    美食類型: ["日本菜", "新派亞洲菜"],
    菜式: ["烏冬", "甜品"],
    comment: "(500+)",
  },
  {
    id: 5,
    name: "莊意麵 Chong Noddle",
    img: more,
    hot: true,
    mark: 4.6,
    distance: 0.3,
    time: "15 - 20",
    discount: "免運費",
    美食類型: ["意大利菜", "亞洲菜", "港式菜"],
    菜式: ["意大利粉", "酒類"],
    comment: "(500+)",
  },
  {
    id:6,
    name: "⭐ BurgerMa 漢堡嗎",
    charge: 250,
    img: more,
    hot: true,
    mark: 4.8,
    distance: 0.6,
    time: "20 - 25",
    discount: "免運費",
    提供純素選擇: true,
    美食類型: ["亞洲菜", "健康"],
    菜式: ["三文治", "漢堡包", "零食"],
    comment: "(500+)",
  },
  {
    id:7,
    name: "北京餃子王",
    charge: 100,
    img: more,
    hot: true,
    mark: 4.4,
    distance: 1.2,
    time: "25 - 30",
    discount: 25,
    提供純素選擇: true,
    美食類型: ["亞洲菜", "上海菜","中菜"],
    菜式: ["餃子", "粉麵"],
    comment: "(500+)",
  },
  {
    id:8,
    name: "洋和食",
    img: more,
    mark: 4.5,
    distance: 0.8,
    time: "25 - 40",
    discount: 35,
    提供純素選擇: true,
    美食類型: ["亞洲菜", "日本菜"],
    菜式: ["餃子", "點心", "雞肉"],
    comment: "(500+)",
    special: "Kangaroo's Choice",
  },
  {
    id:9,
    name: "⭐ 丼丼飯 Donburi",
    img: more,
    mark: 4.4,
    distance: 0.8,
    time: "25 - 35",
    discount: 30,
    提供純素選擇: true,
    美食類型: ["亞洲菜", "日本菜"],
    菜式: ["便當", "雞翼", "雞肉"],
    comment: "(500+)",
    special: "Kangaroo's Choice",
  },
  {
    id:10,
    name: "⭐ 泰好味 Thai yummy",
    img: more,
    mark: 4.2,
    distance: 0.8,
    time: "25 - 45",
    discount: 20,
    提供純素選擇: true,
    素食: true,
    美食類型: ["亞洲菜", "新派亞洲菜"],
    菜式: ["雞翼", "雞肉"],
    comment: "(500+)",
    special: "Kangaroo's Choice",
  },
  {
    id: 11,
    name: "圓圓湯水 YuenYuen Soup",
    img: more,
    mark: 4.6,
    distance: 0.5,
    time: "15 - 35",
    discount: 15,
    美食類型: ["亞洲菜", "新派亞洲菜", "飲品"],
    菜式: ["甜品", "點心"],
    comment: "(84)",
  },
  {
    id: 12,
    name: "磨牙漢堡 More Burger",
    hot: true,
    img: more,
    mark: 4.5,
    distance: 0.6,
    time: "15 - 30",
    discount: "免運費",
    美食類型: ["亞洲菜", "美國菜"],
    菜式: ["炸雞", "漢堡包"],
    comment: "(500+)",
  },
  {
    id: 13,
    name: "雲記粥麵 Wang Kee Congee",
    img: more,
    charge: 100,
    mark: 4.3,
    distance: 1.5,
    time: "25 - 45",
    discount: 25,
    美食類型: ["亞洲菜", "港式菜"],
    菜式: ["粉麵", "雞肉"],
    comment: "(500+)",
  },
  {
    id: 14,
    name: "肯炸雞 Ken Fried Chicken",
    charge: 180,
    hot: true,
    img: more,
    mark: 4.2,
    distance: 0.6,
    time: "20 - 40",
    discount: 20,
    美食類型: ["亞洲菜", "美國菜"],
    菜式: ["炸雞", "漢堡包"],
    comment: "(500+)",
  }
  
];

export {AllRestaurantData};
