const FoodItemData = [
  {
    id: 1,
    hot: true,
    set: true,
    nameHK: "和牛漢堡套餐",
    nameEN: "Wagyu Burger Set",
    price: 56,
  },
  {
    id: 2,
    hot: true,
    set: true,
    nameHK: "芝士漢堡套餐",
    nameEN: "Cheese Burger Set",
    price: 41,
  },
  {
    id: 3,
    set: true,
    nameHK: "辣雞肉漢堡套餐",
    nameEN: "Spicy Hot Chicken Burger Set",
    price: 50,
  },
  {
    id: 4,
    set: true,
    nameHK: "照燒雞肉漢堡套餐",
    nameEN: "Chicken Burger Set",
    price: 52,
  },
  {
    id: 5,
    set: true,
    nameHK: "蝦堡套餐",
    nameEN: "Shrimp Burger Set",
    price: 52,
  },
  {
    id: 6,
    set: true,
    nameHK: "魚柳漢堡套餐",
    nameEN: "Fish Burger Set",
    price: 52,
  },
  {
    id: 7,
    hot: true,
    burger: true,
    nameHK: "和牛漢堡",
    nameEN: "Wagyu Burger",
    price: 33,
  },
  {
    id: 8,
    hot: true,
    burger: true,
    nameHK: "芝士漢堡",
    nameEN: "Chesse Burger",
    price: 32,
  },
  {
    id: 9,
    burger: true,
    nameHK: "辣雞肉漢堡",
    nameEN: "Spicy Hot Chicken Burger",
    price: 38,
  },
  {
    id: 10,
    burger: true,
    nameHK: "照燒雞肉漢堡",
    nameEN: "Chicken Burger",
    price: 37,
  },
  {
    id: 11,
    burger: true,
    nameHK: "美味蝦堡",
    nameEN: "Shrimp Burger",
    price: 35,
  },
  {
    id: 12,
    burger: true,
    nameHK: "魚柳漢堡",
    nameEN: "Fish Burger",
    price: 36,
  },
  {
    id: 13,
    fry: true,
    hot: true,
    nameHK: "大薯條",
    nameEN: "Large Fries",
    price: 24,
  },
  {
    id: 14,
    fry: true,
    nameHK: "細薯條",
    nameEN: "Small Fries",
    price: 18,
  },
  {
    id: 15,
    fry: true,
    nameHK: "脆炸雞塊",
    nameEN: "Nuggets",
    price: 25,
  },
  {
    id: 16,
    fry: true,
    nameHK: "脆炸雞腿",
    nameEN: "Fried Chicken Leg",
    price: 29,
  },
  {
    id: 17,
    drinks: true,
    hot: true,
    nameHK: "凍奶茶",
    nameEN: "Iced Milk Tea",
    price: 25,
  },
  {
    id: 18,
    drinks: true,
    nameHK: "凍咖啡",
    nameEN: "Iced Coffee",
    price: 26,
  },
  {
    id: 19,
    drinks: true,
    nameHK: "可樂",
    nameEN: "Coke",
    price: 15,
  },
  {
    id: 20,
    drinks: true,
    nameHK: "橙汁",
    nameEN: "Orange Juice",
    price: 20,
  },
  {
    id: 21,
    dessert: true,
    hot: true,
    nameHK: "芒果布丁",
    nameEN: "Mango Pudding",
    price: 25,
  },
  {
    id: 22,
    dessert: true,
    hot: true,
    nameHK: "芝士蛋糕",
    nameEN: "Chessee Cake",
    price: 29,
  },
  {
    id: 23,
    dessert: true,
    nameHK: "雲呢拿雪糕",
    nameEN: "Vanilla Ice Cream",
    price: 32,
  },
  {
    id: 24,
    dessert: true,
    nameHK: "士多啤梨雪糕",
    nameEN: "Strawberry Ice Cream",
    price: 32,
  },
];

export { FoodItemData };
